name: CIDAB
on:
  push:
    branches:
      - main
jobs:
  preety_codebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i
      - name: lint
        run: npm run lint


  
